spring :
  profiles :
    active :
      - dog
      - EN
      - qa
vkg :
  username : superuser
  password : masterPassword
  jdbcurl : someURLforDB

---

spring :
  profiles : prod
vkg :
  username: PRODuser
  password: PRODPassword
  jdbcurl: PRODURLforDB